// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<your_key>',
    appId: '1:938235612443:web:2df4e875e786d14c0d17be',
    messagingSenderId: '938235612443',
    projectId: 'discussify-71059',
    authDomain: 'discussify-71059.firebaseapp.com',
    storageBucket: 'discussify-71059.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-lKQvslzhB-K992Nhd21kI1p4qW9M798',
    appId: '1:938235612443:android:5bf95b7f4cd07f680d17be',
    messagingSenderId: '938235612443',
    projectId: 'discussify-71059',
    storageBucket: 'discussify-71059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEUTWwglCv5PyRU8PBZ4tUfhVOFJm48A8',
    appId: '1:938235612443:ios:6d641b9a538be0090d17be',
    messagingSenderId: '938235612443',
    projectId: 'discussify-71059',
    storageBucket: 'discussify-71059.appspot.com',
    iosBundleId: 'com.example.discussify',
  );
}
